# .gitleaks.toml

# Rules for gitleaks to scan for sensitive information
[[rules]]
regex = 'API[_-]?KEY'
description = "Search for API keys"

[[rules]]
regex = 'SECRET[_-]?KEY'
description = "Search for secret keys"

[[rules]]
regex = 'AUTH[_-]?TOKEN'
description = "Search for authentication tokens"

[[rules]]
regex = 'ACCESS[_-]?KEY[_-]?ID'
description = "Search for access key IDs"

[[rules]]
regex = 'PRIVATE[_-]?KEY'
description = "Search for private keys"

[[rules]]
regex = 'DATABASE[_-]?PASSWORD'
description = "Search for database passwords"

[[rules]]
regex = 'DB[_-]?PASSWORD'
description = "Search for database passwords (abbreviated)"

[[rules]]
regex = 'DB[_-]?USER'
description = "Search for database usernames"

[[rules]]
regex = 'DB[_-]?NAME'
description = "Search for database names"

[[rules]]
regex = 'DB[_-]?HOST'
description = "Search for database hosts"

[[rules]]
regex = 'ENCRYPTION[_-]?KEY'
description = "Search for encryption keys"

[[rules]]
regex = 'TOKEN[_-]?SECRET'
description = "Search for token secrets"

[[rules]]
regex = 'USERNAME'
description = "Search for generic usernames"

[[rules]]
regex = 'EMAIL'
description = "Search for email addresses"

[[rules]]
regex = 'PHONE[_-]?NUMBER'
description = "Search for phone numbers"

[[rules]]
regex = 'SSN'
description = "Search for social security numbers"

[[rules]]
regex = 'CREDIT[_-]?CARD[_-]?NUMBER'
description = "Search for credit card numbers"

[[rules]]
regex = 'API[_-]?SECRET[_-]?KEY'
description = "Search for API secret keys"

[[rules]]
regex = 'AWS[_-]?SECRET[_-]?ACCESS[_-]?KEY[_-]?ID'
description = "Search for AWS secret access key IDs"

[[rules]]
regex = 'GITHUB[_-]?TOKEN'
description = "Search for GitHub tokens"

[[rules]]
regex = 'BITBUCKET[_-]?TOKEN'
description = "Search for Bitbucket tokens"

[[rules]]
regex = 'SLACK[_-]?TOKEN'
description = "Search for Slack tokens"

[[rules]]
regex = 'TWITTER[_-]?TOKEN'
description = "Search for Twitter tokens"
