name: Baseline Scan

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Baseline Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://p-aspen.github.io/easybuggy/src/main/webapp'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
      - name: Download ZAP Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-baselinescan-report
          path: ${{github.workspace}}/reports/zap-baseline_report.html


