ybugname: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          ref: ${{ github.event.pull_request.head.ref }}
    - name: Build the Docker image
      run: docker build . -t easybuggy:local # Build container image
    - name: Run Docker image
      run: docker run -p 8080:8080 easybuggy:local # Start easybuggy
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://localhost:8080'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
  kill:
    runs-on: ubuntu-latest
    steps:
      - run: docker kill easybuggy:local
    
