on:
    push:
      branches: [ master ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Full Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.push_request.head.ref }}
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://p-aspen-org.github.io/easybuggy/src/main/webapp'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a '
      - name: Download ZAP Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-fullscan_report
          path: ${{github.workspace}}/reports/zap-fullscan_report.html
   