# name: zapfull-security-scan
# on:
#   push:
#     branches: [ master ]
  
# jobs:   
#   scan:
#     runs-on: ubuntu-latest
#     steps: 
  
#     - name: OWASP ZAP Full Scan
#       uses: zaproxy/action-full-scan@v0.1.0
#       with:
#         target: "https://p-aspen-org.github.io/easybuggy/src/main/webapp/"

#     - name: Download ZAP Scan Report
#       uses: actions/upload-artifact@v2
#       with:
#         name: zap-scan-report
#         path: zap-report.html

# on: [push]

# jobs:
#   zap_scan:
#     runs-on: ubuntu-latest
#     name: Scan the webapplication
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           ref: ${{ github.event.pull_request.head.ref }}
#         #   ref: master
#       - name: ZAP Scan
#         uses: zaproxy/action-full-scan@v0.10.0
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
#           target: 'https://p-aspen-org.github.io/easybuggy/src/main/webapp/'
#           rules_file_name: '.zap/rules.tsv'
#           cmd_options: '-a'

name: Baseline Scan

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://p-aspen.github.io/easybuggy/src/main/webapp/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
