name: zapfull-security-scan
on:
  push:
    branches: [ master ]
  
jobs:   
  scan:
    runs-on: ubuntu-latest
    steps: 
  
    - name: OWASP ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.1.0
      with:
        target: "https://p-aspen-org.github.io/easybuggy/src/main/webapp/"

    - name: Download ZAP Scan Report
      uses: actions/upload-artifact@v2
      with:
        name: zap-scan-report
        path: zap-report.html
