name: zapfull-security-scan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:     
    # - name: OWASP ZAP Full Scan
    #   uses: zaproxy/action-full-scan@v0.1.0
    #   with:
    #     target: "http://localhost:8080"

    - name: Start ZAP Proxy      
      run: zap.sh -daemon -port 8090
    - name: Proxy
      run: |
        export http_proxy=http://localhost:8080
        export https_proxy=http://localhost:8080
  
    - name: Run ZAP Full Scan
      run: |
        zap-cli --zap-url http://localhost:8080 -t http://localhost:8080 -g gen.conf -x zap-report.html -r

    - name: Download ZAP Scan Report
      uses: actions/upload-artifact@v2
      with:
        name: zap-scan-report
        path: zap-report.html
