name: SonarCloud Scan

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
<<<<<<< HEAD
    - name: Build with Maven
      run:  mvn -B verify sonar:sonar -Dsonar.projectKey=P-Aspen-Org_easybuggy -Dsonar.organization=p-aspen-org -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN
=======
    - name: Build with Maven cloud
      run:  mvn -B verify sonar:sonar -Dsonar.projectKey=P-Aspen-Org_easybuggy -Dsonar.organization=p-aspen-org -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN -Dsonar.qualitygate.wait=true
>>>>>>> cf3dc724260f1d8881ee3bfe7cdfa343deed2219
      env:
        GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
        SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
